Upgrade PyLD to 2.0.3
ThePalaceProject/circulation pull request #154
Opened 2022-01-21 11:24 UTC by RishiDiwanTT

* load_document signature changed
* load_document return type schema changed

## Description

A described above

## Motivation and Context

PyLD was outdated (1.0.4)

## How Has This Been Tested?
Api and Core unit tests are passing
Not sure if manual testing is required

## Checklist

- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.

2022-01-25 12:21 UTC, RishiDiwanTT commented
@jonathangreen Forgot to add you as reviewer

2022-01-25 17:13 UTC, tdilauro requested changes
The changes here look good; however, there are some conflicts with the most up-to-date `main` branch that need to be resolved.

2022-01-26 15:19 UTC, jonathangreen approved these changes

2022-01-26 15:38 UTC, tdilauro approved these changes
Looks good to me! 🥇

2022-01-26 15:40 UTC, merged