Feature/docker arm versions
ThePalaceProject/circulation pull request #165
Opened 2022-01-26 21:24 UTC by aseefahmed

## Description

Right now we only build our docker images for a single platform. We should also build ARM versions of our docker images for use with M1 Macbooks and AWS ARM instances.

## Motivation and Context

Add the additional parameters to our docker builds to build and push images for ARM platforms as well as our current builds.

## How Has This Been Tested?

PR with images building for ARM as well as x86

2022-01-26 21:29 UTC, aseefahmed commented
@jonathangreen to review

2022-01-26 22:22 UTC, jonathangreen commented
This builds and pushes an arm version of the image, but it doesn't do any tests on it. Can you also run the tests scripts on the arm versions of the image?

2022-01-26 22:23 UTC, jonathangreen requested changes
This builds and pushes an arm version of the image, but it doesn't do any tests on it. Can you also run the tests scripts on the arm versions of the image?

2022-01-26 22:25 UTC, aseefahmed commented
> This builds and pushes an arm version of the image, but it doesn't do any tests on it. Can you also run the tests scripts on the arm versions of the image?

will have a try

2022-01-27 20:04 UTC, aseefahmed commented
@jonathangreen to review

2022-01-28 17:15 UTC, jonathangreen requested changes

2022-01-28 17:15 UTC, jonathangreen commented on .github/workflows/test-build.yml
> +      - name: Build circ-scripts image (linux/amd64)
Instead of copy pasting these steps you should be able to use a build matrix here.

2022-01-28 17:15 UTC, jonathangreen commented on .github/workflows/test-build.yml
> +      - name: Build circ-scripts image (linux/amd64)
```yaml
    strategy:
      fail-fast: false
      matrix:
        platform: ["linux/amd64", "linux/arm64"]
```

2022-01-31 15:45 UTC, aseefahmed commented
@jonathangreen to review

2022-02-01 02:12 UTC, jonathangreen approved these changes

2022-02-01 02:18 UTC, merged