Update Dockerfile
ThePalaceProject/circulation pull request #170
Opened 2022-01-28 07:48 UTC by aseefahmed

## Description

Right now, docker chacing is not doing as expected. We need to find a way to improve docker caching layers and minimize build time. 

## Motivation and Context

Almost the entire `simplified_app.sh` file does not actually require source code. It does an apt-get update, and installs some packages. Then it installs python poetry. All of this is reasonably time consuming and does not need source code. 

Then we pull in the project dependancies. This also does not require source code, but this does require the the poetry files (`pyproject.toml` and `poetry.lock`). 

Then the final step requires our source code. If we split the docker build process into layers like this, then we can more effectively use layer caching. 

The proposal here is to split base into 3 different layers:

- Setup not requiring any of our code
- Setup requiring our dependancies files
- Setup requiring our code

## How Has This Been Tested?

Containers have been run and tested

2022-01-28 08:50 UTC, aseefahmed commented
@jonathangreen  to review

2022-01-28 16:55 UTC, jonathangreen requested changes

2022-01-28 16:55 UTC, jonathangreen commented on docker/Dockerfile
> +COPY ./docker/simplified_app.sh /ls_build/
The files in the docker folder don't change very often. You should be able to still do 

```dockerfile
COPY ./docker /ls_build
RUN /bin/bash -c "/ls_build/simplified_app.sh \
      && /ls_build/logrotate.sh"
``` 

You can remove the parts of `simplified_app.sh` that depend on `poetry.lock` & `pyproject.toml` and put them into a different script.

2022-01-28 16:55 UTC, jonathangreen commented on docker/Dockerfile
> +COPY --chown=1000:1000 poetry.lock pyproject.toml /var/www/circulation/
Then after this line you can run your new script that installs the dependencies using poetry

2022-01-28 22:28 UTC, aseefahmed commented
@jonathangreen to review. it seems not need to create a seperate script for poetry if we use 

```dockerfile
COPY ./docker /ls_build
COPY --chown=1000:1000 poetry.lock pyproject.toml /var/www/circulation/
```
`

2022-01-28 22:31 UTC, jonathangreen commented
We don't need a seperate script for poetry, but if we are trying to make our layer caches as efficient as we can, then it makes sense to have a layer with: 
- The main os + updates + packages we need installed
- The python dependencies we need installed
- The app installed

Since the OS packages don't change very often, the python dependencies change more often, but not that often, and the code changes every time.

2022-01-28 23:21 UTC, aseefahmed commented
how is that now @jonathangreen 

```dockerfile
COPY ./docker /ls_build
COPY --chown=1000:1000 poetry.lock pyproject.toml /var/www/circulation/

RUN /bin/bash -c "/ls_build/simplified_app.sh"

RUN /bin/bash -c "/ls_build/install_python_packages.sh \
      && /ls_build/logrotate.sh"

COPY --chown=1000:1000 . /var/www/circulation
```

2022-01-31 15:45 UTC, aseefahmed commented
@jonathangreen to reivew

2022-02-01 11:40 UTC, jonathangreen approved these changes

2022-02-01 11:41 UTC, merged