Proof of concept for exact terms json based search
ThePalaceProject/circulation pull request #368
Opened 2022-05-20 07:15 UTC by RishiDiwanTT

## Description
The following have been proved through testing (unit and manual)
- Basic exact matches
- And'd queries
- Or'd queries
- Mixed And'd and Or'd queries
- <> type queries
- Nested And'd and Or'd queries
- "Nested Type" ES object queries with And/Or operators

To move from POC to Production ready code the following is required
- Test/implement all supported keys
- Test/implement exception cases
- Test/implement API entrypoint for json based search
- Inline documentation for all new/modified code

## Motivation and Context
An advanced and exact terms based search was required to allow more control to the administrators
More details: https://www.notion.so/lyrasis/Proof-of-concept-Create-new-search-API-with-support-for-additional-metadata-elements-ef25fd3ec79241b9a003683403be752c

## How Has This Been Tested?

## Checklist

- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.

2022-06-03 09:55 UTC, io7m commented on core/external_search.py
> +            es_query = Range(**{key: {op: value}})
I'm inclined to add a `raise` here if we encounter another `Operator` here. We want the code to loudly fail when a new operator is added, rather than being silently incomplete.

2022-06-03 09:56 UTC, io7m commented on core/external_search.py
> +            joined_query = Bool(should=to_join)
Same goes here. We may never add a new `Conjunctive`, but the code should fail here if we ever do rather than being silently wrong.

2022-06-03 09:57 UTC, io7m requested changes
Seems good, except for a couple of statements that could use some paranoid safety measures. :slightly_smiling_face: 

There's also a merge conflict now.

2022-06-03 10:27 UTC, RishiDiwanTT commented on core/external_search.py
> +            es_query = Range(**{key: {op: value}})
Yes, this is in draft for this reason, a lot of fine tuning is required, this is just to know whether the POC is in the right direction so far

2022-06-13 11:11 UTC, RishiDiwanTT commented
@io7m @tdilauro @dwilcox I will continue down this path, and move this from a POC state to a Production state by adding more tests, defensive checks and an API endpoint

2022-06-21 07:22 UTC, RishiDiwanTT commented on core/external_search.py
> +            es_query = Range(**{key: {op: value}})
We now have exception cases

2022-07-08 05:27 UTC, merged