Changed socket timeouts for SIP2 connections to 2 seconds
ThePalaceProject/circulation pull request #919
Opened 2023-03-14 12:17 UTC by RishiDiwanTT

## Description
To ensure speedy failures for faulty SIP2 providers
During a timeout the API will respond with a 
`{"type": "http://librarysimplified.org/terms/problem/remote-integration-failed", "title": "Failure contacting external service", "status": 502, "detail": "The server tried to access 127.0.0.1 but the third-party service experienced an error."}`

## Motivation and Context
We have seen an incident twice in the past two weeks, where a SIP integration has gone offline, and this has caused one of our CM to become unresponsive for all the libraries in the CM. In order to reduce this happening, we should reduce the timeout that we wait for a SIP connection to respond.

## How Has This Been Tested?

## Checklist

- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.

2023-03-14 13:26 UTC, io7m approved these changes
Looks good! :rocket:

2023-03-14 13:47 UTC, jonathangreen requested changes
I'd like to hold off on merging this one, until we test two things:
- Write a small benchmark and see if 2s is a long enough timeout for our existing production servers. 
- Make sure that in the event we do timeout, we are getting a reasonable log message that we can query for. 
  - I see we are re-raising the exception, but I'm not sure what that will end up looking like in out logs.

2023-04-04 13:49 UTC, jonathangreen commented
Since the https://github.com/ThePalaceProject/circulation/pull/893 is now deployed to production, we can get some real statistics from Cloudwatch insights about how long our connections are taking.

Cloudwatch insights query I used:
```
fields @timestamp, @message, @logStream, @log
| filter @logStream like "uwsgi" and message like "authenticated_patron - authenticate: Completed."
| parse message 'authenticated_patron - authenticate: Completed. (elapsed time: * seconds)' as seconds
| stats pct(seconds,98), avg(seconds), count() as c by name, @logStream
| sort c desc
```

The SIP2 p98 connections time ends up at about 1.5 seconds overall. 

If we wanted to use p99 as our metric here, we would end up with a time of 2.5 seconds, which would imply we should increase this from 2 to 3 seconds for a timeout. So it seems this value is fairly reasonable. 

Maybe to be on the safe side, we could bump it up to 3 second @RishiDiwanTT, then we can get it out to production and monitor how many connections are failing.

2023-04-04 14:01 UTC, jonathangreen approved these changes
🚀

2023-04-05 06:00 UTC, merged